# Generated by Django 2.0.2 on 2018-09-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iccdbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('idstatus', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
