# Generated by Django 2.0.2 on 2018-09-26 13:52

import django.core.validators
from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('iccdbook', '0004_auto_20180926_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, default='you@somewhere.com', max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='name@domain.com', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='streetAddress',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='telephone',
            field=models.CharField(blank=True, default='7045550000', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Area code and number', regex='^\\d{3}-\\d{3}-\\d{4}$|^\\d{10}$|^\\d{3} \\d{3} \\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='zip',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True),
        ),
    ]
