# Generated by Django 2.0.2 on 2018-09-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iccdbook', '0006_auto_20180926_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nfccardid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
